extends Node

const ABILITY_CAST_START = "ABILITY_CAST_START"
const ABILITY_CAST_RESULT = "ABILITY_CAST_RESULT"
const ABILITY_CAST_FAILED_RESOURCE_MISSING = "ABILITY_CAST_FAILED_RESOURCE_MISSING"
const RESOURCE_UPDATE = "RESOURCE_UPDATE"
const BUFF_APPLIED = "BUFF_APPLIED"
const DEBUFF_APPLIED = "DEBUFF_APPLIED"
const UNIT_STATE_CHANGED = "UNIT_STATE_CHANGED"

static func to_array():
	return [
		ABILITY_CAST_START,
		ABILITY_CAST_RESULT,
		RESOURCE_UPDATE,
		BUFF_APPLIED,
		DEBUFF_APPLIED,
		UNIT_STATE_CHANGED
	]
