class_name GameFlag
extends Node

enum Enum {
	QUEST_TALKED_TO_ALFOND,
	INTRO_PLAYED,
	INTRO_TALKED_TO_ALFOND,
	INTRO_PICKED_UP_BACKPACK,
	INTRO_LEFT_HOUSE,
	BOSS_ELEMENTAL_SLIME_DEFEATED,
	BOSS_MEGA_SLIME_DEFEATED,
	BOSS_VISJALA_DEFEATED
}
