class_name SpellSchool
enum Enum {
	PHYSICAL,
	FIRE,
	FROST,
	WIND,
	EARTH,
	LIGHT,
	SHADOW,
	NATURE,
	WATER,
	THUNDER,
	GRAVITY
}

const SPELLPOWER_STAT = {
	Stat.Enum.ATTACK_POWER: Enum.PHYSICAL,
	Stat.Enum.FIRE_SPELL_POWER: Enum.FIRE,
	Stat.Enum.FROST_SPELL_POWER: Enum.FROST,
	Stat.Enum.WIND_SPELL_POWER: Enum.WIND,
	Stat.Enum.EARTH_SPELL_POWER: Enum.EARTH,
	Stat.Enum.LIGHT_SPELL_POWER: Enum.LIGHT,
	Stat.Enum.SHADOW_SPELL_POWER: Enum.SHADOW,
	Stat.Enum.NATURE_SPELL_POWER: Enum.NATURE,
	Stat.Enum.WATER_SPELL_POWER: Enum.WATER,
	Stat.Enum.THUNDER_SPELL_POWER: Enum.THUNDER,
	Stat.Enum.GRAVITY_SPELL_POWER: Enum.GRAVITY,
}

const SPELL_RESISTANCE_STAT = {
	Stat.Enum.ARMOR: Enum.PHYSICAL,
	Stat.Enum.FIRE_RESISTANCE: Enum.FIRE,
	Stat.Enum.FROST_RESISTANCE: Enum.FROST,
	Stat.Enum.WIND_RESISTANCE: Enum.WIND,
	Stat.Enum.EARTH_RESISTANCE: Enum.EARTH,
	Stat.Enum.LIGHT_RESISTANCE: Enum.LIGHT,
	Stat.Enum.SHADOW_RESISTANCE: Enum.SHADOW,
	Stat.Enum.NATURE_RESISTANCE: Enum.NATURE,
	Stat.Enum.WATER_RESISTANCE: Enum.WATER,
	Stat.Enum.THUNDER_RESISTANCE: Enum.THUNDER,
	Stat.Enum.GRAVITY_RESISTANCE: Enum.GRAVITY,
}

const RESISTANCE = {
	Enum.PHYSICAL: Stat.Enum.ARMOR,
	Enum.FIRE: Stat.Enum.FIRE_RESISTANCE,
	Enum.FROST: Stat.Enum.FROST_RESISTANCE,
	Enum.WIND: Stat.Enum.WIND_RESISTANCE,
	Enum.EARTH: Stat.Enum.EARTH_RESISTANCE,
	Enum.LIGHT: Stat.Enum.LIGHT_RESISTANCE,
	Enum.SHADOW: Stat.Enum.SHADOW_RESISTANCE,
	Enum.NATURE: Stat.Enum.NATURE_RESISTANCE,
	Enum.WATER: Stat.Enum.WATER_RESISTANCE,
	Enum.THUNDER: Stat.Enum.THUNDER_RESISTANCE,
	Enum.GRAVITY: Stat.Enum.GRAVITY_RESISTANCE,
}

const SPELLPOWER = {
	Enum.PHYSICAL: Stat.Enum.ATTACK_POWER,
	Enum.FIRE: Stat.Enum.FIRE_SPELL_POWER,
	Enum.FROST: Stat.Enum.FROST_SPELL_POWER,
	Enum.WIND: Stat.Enum.WIND_SPELL_POWER,
	Enum.EARTH: Stat.Enum.EARTH_SPELL_POWER,
	Enum.LIGHT: Stat.Enum.LIGHT_SPELL_POWER,
	Enum.SHADOW: Stat.Enum.SHADOW_SPELL_POWER,
	Enum.NATURE: Stat.Enum.NATURE_SPELL_POWER,
	Enum.WATER: Stat.Enum.WATER_SPELL_POWER,
	Enum.THUNDER: Stat.Enum.THUNDER_SPELL_POWER,
	Enum.GRAVITY: Stat.Enum.GRAVITY_SPELL_POWER,
}

static func get_spell_power_for_stat(stat: Stat.Enum) -> SpellSchool.Enum:
	return SPELLPOWER_STAT[stat]
	
static func get_spell_resistance_for_stat(stat: Stat.Enum) -> SpellSchool.Enum:
	return SPELL_RESISTANCE_STAT[stat]
